---
name: Quality Assurance
on:
  push:
    branches-ignore:
      - master

jobs:
    build:
        name: '[Build] Node.js ${{ matrix.nodejs }}'
        runs-on: ubuntu-latest
        strategy:
            matrix:
                nodejs: ['12']
        steps: 
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.nodejs }}
            - run: npm install
            - run: npm run argon2-rebuild
