name: directus

type: nodejs:12

dependencies:
    python3:
       pipenv: '*'

variables:
    env:
        TEMPLATE_PROFILE: directus

hooks:
    build: |
        set -e
        # Rebuild argon2 to fix upstream issue (See https://docs.directus.io/guides/installation/plesk/#bootstrap-directus).
        npm run argon2-rebuild

        # Template maintenance tasks.
        .platform-scripts/template/verify_updater.sh
    deploy: |
        set -e
        # Installs the database and sets up the initial admin user. Only run on first deploy.
        if [ ! -f var/platformsh.installed ]; then
            echo 'Bootstrapping Directus on first deploy...'

            export PROJECT_NAME='Directus on Platform.sh'
            export ADMIN_EMAIL='admin@example.com'
            export ADMIN_PASSWORD='password'
            
            npx directus bootstrap

            # Create file that indicates first deploy and installation has been completed.
            touch var/platformsh.installed
        fi; 

relationships:
    database: "db:postgresql"
    rediscache: "cacheredis:redis"
    redisratelimit: "ratelimitredis:redis"

web: 
    commands:
        start: npx directus start

disk: 1024

mounts:
    # Directory to track first deploy.
    'var':
        source: local
        source_path: var
    # Allow for file uploads.
    'uploads':
        source: local
        source_path: uploads

# Auto-update source operation
source:
    operations:
        platform_update_dependencies:
            command: .platform-scripts/template/operation.update_template.sh

timezone: "America/New_York"

crons:
    # Auto-update environment verification.
    update:
        # spec: '51 2 * * *' # Create environment just before update.
        spec: '0 11 * * *' # Create environment just before update.
        cmd: .platform-scripts/template/verify_updater.sh
    # Auto-update cron job.
    update:
        spec: '0 3 * * *' # Update template.
        cmd: .platform-scripts/template/crons.update.sh
