---
# Retrieving a Platform.sh development environment URL, which is then used to run subsquent workflows.
name: Post-deployment tests

on:
  push:
    branches-ignore:
      - master

jobs:
    build:
        runs-on: ubuntu-latest
        name: 'Get environment URL'
        outputs:
            commit_status: ${{ steps.status.outputs.env_status }}
            env_url: ${{ steps.url.outputs.env_url }}  
        steps: 
            - uses: actions/checkout@v2
            - name: 'Await deployment'
              id: wait
              run: |
                COMMIT_STATUS="pending"
                until [ "$COMMIT_STATUS" == "success" ] || [ "$COMMIT_STATUS" == "failure" ]; do
                  sleep 10
                  COMMIT_STATUS=$(curl -s https://api.github.com/repos/platformsh-templates/directus/statuses/$GITHUB_SHA  | jq -r '.[0].state')
                  echo "Waiting for Platform.sh environment to deploy ...."
                done
                echo "Environment deployed. Finished."
            - name: 'Pass status'
              id: status
              run: |
                COMMIT_STATUS=$(curl -s https://api.github.com/repos/platformsh-templates/directus/statuses/$GITHUB_SHA  | jq -r '.[0].state')
                echo "::set-output name=env_status::$COMMIT_STATUS"
            - name: 'Pass URL'
              id: url
              run: |
                ENV_URL=$(curl -s https://api.github.com/repos/platformsh-templates/directus/statuses/$GITHUB_SHA  | jq -r '.[0].target_url')
                echo "::set-output name=env_url::$ENV_URL"
    check:
        name: 'Check results'
        runs-on: ubuntu-latest
        needs: build
        steps: 
            - run: |
                echo "${{ needs.build.outputs.commit_status }}"
                echo "${{ needs.build.outputs.env_url }}"
#     test:
#         name: 'Status tests'
#         runs-on: ubuntu-latest
#         steps:
#             - name: 'Homepage should deploy successfully'
#               uses: lakuapik/gh-actions-http-status@v1
#               with:
#                 sites: '["https://pr-8-ojug23i-o3fc5w4n5iumy.eu-3.platformsh.site/"]'
#                 expected: '[302]'
#             - name: 'No items should be defined'
#               uses: lakuapik/gh-actions-http-status@v1
#               with:
#                 sites: '["https://pr-8-ojug23i-o3fc5w4n5iumy.eu-3.platformsh.site/items"]'
#                 expected: '[404]'
            
