---
# Retrieving a Platform.sh development environment URL, which is then used to run subsquent workflows.
name: Post-deployment tests

on:
  push:
    branches-ignore:
      - master

jobs:
    build:
        runs-on: ubuntu-latest
        name: 'Get environment URL'
        outputs:
            commit_status: ${{ steps.status.outputs.env_status }}
            env_url: ${{ steps.url.outputs.env_url }}  
        steps: 
            - uses: actions/checkout@v2
            - name: 'Await deployment'
              id: wait
              run: |
                COMMIT_STATUS="pending"
                until [ "$COMMIT_STATUS" == "success" ] || [ "$COMMIT_STATUS" == "failure" ]; do
                  sleep 10
                  COMMIT_STATUS=$(curl -s https://api.github.com/repos/$GITHUB_REPOSITORY/statuses/$GITHUB_SHA  | jq -r '.[0].state')
                  echo "Waiting for Platform.sh environment to deploy ...."
                done
                echo "Environment deployed. Finished."
            - name: 'Pass status'
              id: status
              run: |
                COMMIT_STATUS=$(curl -s https://api.github.com/repos/$GITHUB_REPOSITORY/statuses/$GITHUB_SHA  | jq -r '.[0].state')
                echo "::set-output name=env_status::$COMMIT_STATUS"
            - name: 'Pass URL'
              id: url
              run: |
                ENV_URL=$(curl -s https://api.github.com/repos/$GITHUB_REPOSITORY/statuses/$GITHUB_SHA  | jq -r '.[0].target_url')
                echo "::set-output name=env_url::$ENV_URL"
    # Need conditionals so this only runs on successful deployments
    # Activity script: integration target_url should be deployed site on success, but shareable activity on failure.
    # Needs to run on all pushes, don't ignore master
    test:
        name: 'Status tests'
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: 'Homepage should deploy successfully'
              uses: lakuapik/gh-actions-http-status@v1
              with:
                sites: '["${{ needs.build.outputs.env_url }}"]'
                expected: '[301]'
            - name: 'No items should be defined'
              uses: lakuapik/gh-actions-http-status@v1
              with:
                sites: '["${{ needs.build.outputs.env_url }}"]'
                expected: '[301]'
    audit:
        name: 'Lighthouse'
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Audit live URL
              uses: jakejarvis/lighthouse-action@master
              with:
                url: ${{ needs.build.outputs.env_url }}
            - name: View results
              run: |
                  echo "$OUTPUT_FILENAME"
                  ls -a report
            - name: Upload results as an artifact
              uses: actions/upload-artifact@master
              with:
                name: report
                path: './report'
            
