---
# Retrieving a Platform.sh development environment URL, which is then used to run subsquent workflows.
name: Get Platform.sh URL
on:
  push:
    branches-ignore:
      - master

jobs:
    build:
        name: 'Retrieve Environment URL'
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v2
            - name: Get the current status
              if: ${{ success() }}
              run: |
                echo "$GITHUB_SHA"
                COMMIT_STATUS=$(curl -s https://api.github.com/repos/platformsh-templates/directus/statuses/$GITHUB_SHA  | jq -r '.[0].state')
                until [ "$COMMIT_STATUS" == "success" ] || [ "$COMMIT_STATUS" == "failure" ]; do
                  sleep 10
                  COMMIT_STATUS=$(curl -s https://api.github.com/repos/platformsh-templates/directus/statuses/$GITHUB_SHA  | jq -r '.[0].state')
                done
