name: Audit live site
on:
  push:
    branches-ignore:
      - master
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - name: Audit live URL
      uses: jakejarvis/lighthouse-action@master
      with:
        url: 'https://pr-8-ojug23i-o3fc5w4n5iumy.eu-3.platformsh.site/'
    - name: Upload results as an artifact
      uses: actions/upload-artifact@master
      with:
        name: report
        path: './report'
